project:
  type: website
website:
  title: "light/dark renderings in jupyter notebooks"
  repo-url: https://github.com/gordonwoodhull/jupyter-notebook-renderings
  sidebar:
    style: "docked"
    contents:
      - section: 'markdown cells'
        contents:
          - matplotlib-markdown.ipynb
          - plotly-markdown.ipynb
      - section: 'contents shortcode'
        contents:
          - altair-contents.ipynb
          - plotly-contents.ipynb
          - plotnine-contents.ipynb
      - section: 'embed shortcode'
        contents:
          - altair-embed.ipynb
          - bokeh-embed.ipynb
          - great-tables-embed.ipynb
          - matplotlib-embed.ipynb
          - plotly-embed.ipynb
          - plotnine-embed.ipynb
          - pygal-embed.ipynb
          - seaborn-embed.ipynb
brand:
  light: light-brand.yml
  dark: dark-brand.yml
theme:
  light: brand
  dark: [brand, dark-fixups.scss]
format:
  html:
    respect-user-color-scheme: true
    code-tools:
      source: repo
