project:
  type: website
website:
  title: "light/dark renderings in jupyter notebooks"
  sidebar:
    style: "docked"
    contents:
      - section: 'contents shortcode'
        contents:
          - subfigure-contents-shortcode-altair.ipynb
          - subfigure-contents-shortcode-plotly.ipynb
          - subfigure-contents-shortcode-plotnine.ipynb
      - section: 'embed shortcode'
        contents:
          - altair-embed.qmd
          - bokeh-embed.qmd
          - great-tables-embed.qmd
          - matplotlib-embed.qmd
          - plotly-embed.qmd
          - plotnine-embed.qmd
          - pygal-embed.qmd
          - seaborn-embed.qmd
brand:
  light: light-brand.yml
  dark: dark-brand.yml
theme:
  light: brand
  dark: [brand, dark-fixups.scss]
format:
  html:
    respect-user-color-scheme: true